import ('./Endpoints/Beatmap.js');
import ('./Endpoints/Beatmapset.js');
import ('./Endpoints/BeatmapsetFull.js');
import ('./Endpoints/Download.js');
import ('./Endpoints/DownloadStats.js');
import ('./Endpoints/Osz.js');
import ('./Endpoints/OszFull.js');
import ('./Endpoints/Search.js');
import ('./Endpoints/Stats.js');
